def show_lifestyle_menu():
    print("\n-----------------------------------------------------")
    print(" [🏠H] [🏥He] [🚗C] [✈️T] [🛍️S] [🎓Sc] [👵A] [💰B]")
    print("=====================================================")
    print("      🌟 LIFESTYLE & INCENTIVES SELECTOR")
    print("-----------------------------------------------------")
    print(" [H]  HOUSING PROGRAM   (Full Ownership)")
    print(" [He] HEALTHCARE        (Global Coverage)")
    print(" [C]  CAR INCENTIVE     (Luxury/Utility)")
    print(" [T]  TRAVEL & LEISURE  (All-Expense Paid)")
    print(" [S]  SHOPPING SPREE    (Merchant Network)")
    print(" [Sc] SCHOLARSHIP       (Education Fund)")
    print(" [A]  AGED CARE         (Pension Plan)")
    print(" [B]  BUSINESS LOAN     (Zero Interest)")
    print("-----------------------------------------------------")
